### ISSUE TITLE
Section 4.4.2: nonce hiding is also a security property

### ISSUE THREAD

**Issue by cjpatton** [AndAlBo/draft-irtf-cfrg-aead-properties#1]
Nonce hiding implies confidentiality of the nonce passed to the AEAD. To me this makes it more of a security property than strictly a functional one. I would propose moving this up to the security properties section.

**Comment by AndAlBo** [comment]
Agreed. I've moved it to the security properties section, redefined it, and included a note stating that nonce-hiding AEADs do not require a nonce for decryption. 

The issue with that property stems from [[BNT19]](https://eprint.iacr.org/2019/624.pdf), which explicitly changes the AEAD syntax by removing the nonce from decryption in NBE2 schemes. However, I agree it is not about functionality.
