### ISSUE TITLE
Section 4.2.6 on Key Dependent Messages (KDM) security

### ISSUE THREAD

**Issue by jedisct1** [AndAlBo/draft-irtf-cfrg-aead-properties#11]
Bellare and Keelveedhi's paper referenced in the draft show that KDM security is only achievable if the IV and/or keys are non-deterministic. The draft only mentions random IVs, but the paper also proposes a construction where encryption is done using a subkey derived from the original key and additional randomness. 

The results from these papers apply to any AEAD. So, should it be an AEAD property? It's rather a property of higher-level constructions and protocols using AEADs (I think HPKE provides this for example).

One could design an AEAD that requires randomness, but that would be very unusual, and none of these exist AFAIK.  So I'd suggest removing Section 4.2.6.

**Comment by AndAlBo** [comment]
Agreed. I will remove it in the next commit, thanks!
