### ISSUE TITLE
Section 4.4.4. Robustness

### ISSUE THREAD

**Issue by jedisct1** [AndAlBo/draft-irtf-cfrg-aead-properties#15]
> allows the user to choose an arbitrary value l >= 0 for every plaintext and then encrypts it into a ciphertext, which is l bits longer.

This is the first sentence of AEZ's abstract, but it actually doesn't mean much on its own.  We should rather document the purpose of λ (essentially, a security parameter).

**Comment by AndAlBo** [comment]
Done. Moved the property to the appendix and added some security reasoning to the definition.
