### ISSUE TITLE
Section 4.2.5 on Key commitment

### ISSUE THREAD

**Issue by jedisct1** [AndAlBo/draft-irtf-cfrg-aead-properties#7]
Section 4.2.5 is a little bit confusing.

> An AEAD algorithm guarantees that it is difficult to
> find two or more different keys and the same number of potentially
> equal triples of nonce, associated data, and plaintext such that they
> encrypt to the same ciphertext under corresponding keys.

This parses as "it is difficult to find distinct (key, nonce, associated data, plaintext) tuples that encrypt to the same ciphertext". Which looks the same as full commitment.

> In other words, an AEAD scheme guarantees that a ciphertext is a commitment to
>  the key used for an authenticated encryption operation.

And here, the nonce and associated data are lost. 

It is also not obvious that "ciphertext" includes the authentication tag, even though this is the main tool that can provide key commitment.

We'd like to align the AEGIS document with this document.

But in AEGIS, it is difficult to find distinct `(key, nonce, plaintext)`  tuples that share the same associated data and encrypt to the same ciphertext. It is key-committing in the in the receiver-binding game, but that relaxed setting cannot be expressed using the properties set of this document.

It may be more clear to define key commitment in term of the inputs an adversary is allowed to change in order to cause a ciphertext collision.

**Comment by AndAlBo** [comment]
> This parses as "it is difficult to find distinct (key, nonce, associated data, plaintext) tuples that encrypt to the same ciphertext". Which looks the same as full commitment.

In that definition, the keyword "different" before "keys" is crucial; the keys in the tuples must be different, while the rest of the tuples might be the same. I haven't figured out how to make this more explicit yet, but I think it's worth clarifying further.

> It is also not obvious that "ciphertext" includes the authentication tag, even though this is the main tool that can provide key commitment.

Following [[RFC5116]](https://www.ietf.org/archive/id/draft-irtf-cfrg-aead-properties-02.html#RFC5116), we consider the tag to be part of the ciphertext. I will add a note after defining the AEAD operations to emphasize this.

Commitment properties in the draft adhere to CMT-1 and CMT-4(3) notions from [[BH22]](https://eprint.iacr.org/2022/268.pdf) for key commitment and full commitment, respectively. I believe [BH22] is the best paper to follow in this context, given that their notions are intuitive and extensively used to analyze AEADs. However, commitment in the context-restricted setting [[MLGR23]](https://eprint.iacr.org/2023/526.pdf) is an interesting property as well, and it aligns closely with real-life attacks. To address this, I propose adding the following note to the commitment sections:

>Full (key) commitment can be considered in a weaker setting, where certain restrictions on the tuples produced by an adversary are imposed [MLGR23]. For instance, an adversary must find tuples that all share the same associated data value. In such cases, an AEAD algorithm is said to provide full (key) commitment in a restricted setting. The imposed restrictions MUST be listed.

This way, AEGIS provides full commitment in a restricted setting, where an adversary can't vary the associated data.

What do you think about that?

**Comment by jedisct1** [comment]
> Following [[RFC5116]](https://www.ietf.org/archive/id/draft-irtf-cfrg-aead-properties-02.html#RFC5116), we consider the tag to be part of the ciphertext. I will add a note after defining the AEAD operations to emphasize this.

Yes, that should be explicit to avoid any ambiguity. In specifications and implementations, the ciphertext and tag are usually defined as two different things.

> To address this, I propose adding the following note to the commitment sections. [...]
> This way, AEGIS provides full commitment in a restricted setting, where an adversary can't vary the associated data.

Perfect!

> full (key) commitment

Is the emphasis on the key necessary? For consistency, maybe this document could consistently use "full commitment" for that property (as opposed to "key commitment"?)

**Comment by AndAlBo** [comment]
> Is the emphasis on the key necessary? For consistency, maybe this document could consistently use "full commitment" for that property (as opposed to "key commitment"?)

I was considering adding the note to both full commitment and key commitment. However, it might indeed be enough in the full commitment section.

**Comment by jedisct1** [comment]
I guess that can be closed after the changes you made.
