### ISSUE TITLE
Quantum security

### ISSUE THREAD

**Issue by jedisct1** [AndAlBo/draft-irtf-cfrg-aead-properties#8]
In the security properties, maybe it would be worth documenting the security against quantum attacks, in the Q1 and Q2 settings.

**Comment by AndAlBo** [comment]
I will add it in the next commit, and cite [[KLLNP16]](https://tosc.iacr.org/index.php/ToSC/article/download/536/480/1929) for the Q1-Q2 notion.

**Comment by jedisct1** [comment]
I guess that one can be closed. Thank you!
