### ISSUE TITLE
Hardware/software requirements

### ISSUE THREAD

**Issue by jedisct1** [AndAlBo/draft-irtf-cfrg-aead-properties#9]
Some AEADs are very efficient in software, some are very efficient in software, some are very efficient in software only with dedicated instructions (ex: AESNI).

Maybe this is something that should be captured in the implementation properties.

**Comment by yt-nakano** [comment]
AEGIS [1] and Rocca-S [2] can be used as examples of such algorithms. Both use AES round function as a component and can be very efficient with dedicated instructions (e.g. AES-NI). Rocca-S can be also efficient (up to 2 Tbps) on hardware implementation [3].  

[1] https://datatracker.ietf.org/doc/draft-irtf-cfrg-aegis-aead/
[2] https://datatracker.ietf.org/doc/draft-nakano-rocca-s/
[3] https://www.springerprofessional.de/en/an-ultra-high-throughput-aes-based-authenticated-encryption-sche/26619626

**Comment by jedisct1** [comment]
Regarding hardware, anything Keccak-based (such as Kravatte-*) would probably be a better illustration. And ChachaPoly for software.

AES-based constructions are in a different category. They are not good a good fit for software, and even software implementations require some hardware support to be safe and efficient.

That being said, hardware improves, while this document is meant to be future-proof. Especially with SHAKE being required by PQ schemes, it's likely that CPUs will eventually all support Keccak acceleration. GF-NI can also be a game changer. So naming specific constructions that are or are not efficient in software in this document is tricky. That information may not age well.

It's probably better to document what hardware class an AEAD is optimal on: small-area hardware, CPUs with a specific instruction class, general-purpose CPU with 64 bit registers but no specific instruction class, etc.

**Comment by AndAlBo** [comment]
> It's probably better to document what hardware class an AEAD is optimal on: small-area hardware, CPUs with a specific instruction class, general-purpose CPU with 64 bit registers but no specific instruction class, etc.

That's a great idea! I will come back with a version of the definition soon.

**Comment by AndAlBo** [comment]
Something like that:

> **Hardware efficiency**
> 
> Definition. An AEAD algorithm is designed to optimize efficiency on specific classes of hardware.
> 
> Note. Different classes of hardware can be considered. Some AEAD algorithms are tailored to achieve optimal efficiency on CPUs equipped with dedicated cryptographic instructions (e.g., AES-NI). Conversely, others are designed to deliver uniform efficiency across arbitrary hardware, while some are optimized for a particular type of resource-constrained hardware. It is RECOMMENDED to specify the targeted hardware classes. 

I don't have much experience with dedicated hardware implementations, so any comments on that would be greatly appreciated =)

**Comment by jedisct1** [comment]
How about something like:

Definition: the hardware requirements for the AEAD to perform optimally.

Note: Various classes of hardware may be taken into consideration. Certain algorithms are tailored to minimize the area of dedicated hardware implementations, while others are intended to capitalize on general-purpose CPUs, with or without specific instruction sets. It is recommended to specify the minimum platform requirements for the AEAD to fulfill its intended purpose, as well as to match its performance and security claims.

**Comment by AndAlBo** [comment]
Frank, thank you so much!

I replaced the note in f9fe402 and made a slight adjustment to the definition to maintain consistency with others:

>  An AEAD algorithm ensures optimal performance when operating on hardware that complies with the specified requirements.

**Comment by jedisct1** [comment]
Thank you!
